### PR TITLE
Many refactorings

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by alejandro-isaza** [comment]
Why did you close this?

**Comment by adamnemecek** [comment]
I noticed there was a bug but I wasn't on my computer to fix it. Imma create another pull request in a couple of days when I'm back.

**Comment by adamnemecek** [comment]
Fundamentally did you see anything objectionable in the pr?

**Comment by alejandro-isaza** [comment]
No, maybe a couple comments but I'll wait for the next PR. Thanks again!

**Comment by loudinb** [comment]
There is a problem with this commit related to vector addition.  And there is an issue with matrix row or column operations.

In the Vector playground, `let c = a + b`,  results in an error `"type of expression is ambiguous without more context"`.   In the Matrix playground, `var col = A.column(0)`, results in an error `"fatal error: invalid Collection: count differed in successive traversals"`.

I have determined it is a result of the 2nd commit on 12/30, but I do not see what the problem is.

**Comment by alejandro-isaza** [comment]
Ok, thanks for looking into it. I'll have a look.

**Comment by alejandro-isaza** [comment]
That's strange because if I put that same code in an unit tests it passes. Looks like it's something to do with the Playground.

**Comment by alejandro-isaza** [comment]
Ok, should be fixed.

**Pull request closed without merging**
