### PR TITLE
Add replaceRange functionality to RealArray

### PR DESCRIPTION
**Pull request by aidangomez**

### CODE REVIEW

**Comment by alejandro-isaza** [comment]
Make sure that the tests are passing.

**Comment by aidangomez** [comment]
@aleph7 This is ready for merger.

**Comment by aidangomez** [comment]
@aleph7  I'll have to use CollectionType because it's both a SequenceType and Indexable

**Comment by aidangomez** [comment]
@aleph7 Okay, looks like it's ready for merge.

**Pull request merged**
